In [1]:
import numpy as np

1. Criando um kernel gaussiano

In [10]:
size = 3 
sigma=1.0
ax = np.arange(-(size // 2), size // 2 + 1)
print("ax: ")
print(ax)
xx, yy = np.meshgrid(ax, ax)
print("xx: ")
print(xx)
print("yy:")
print(yy)
kernel = np.exp(-(xx**2 + yy**2) / (2 * sigma**2))
print("kernel: ")
print(kernel)
print("kernel sum: ", kernel.sum())
kernel /= kernel.sum()
print("normalized kernel: ")
print(kernel)
print("kernel sum: ", kernel.sum())

ax: 
[-1  0  1]
xx: 
[[-1  0  1]
 [-1  0  1]
 [-1  0  1]]
yy:
[[-1 -1 -1]
 [ 0  0  0]
 [ 1  1  1]]
kernel: 
[[0.36787944 0.60653066 0.36787944]
 [0.60653066 1.         0.60653066]
 [0.36787944 0.60653066 0.36787944]]
kernel sum:  4.897640403536304
normalized kernel: 
[[0.07511361 0.1238414  0.07511361]
 [0.1238414  0.20417996 0.1238414 ]
 [0.07511361 0.1238414  0.07511361]]
kernel sum:  0.9999999999999998


2. Vamos aplicar o kernel a uma imagem exemplo

In [11]:
# Cria uma matriz 5x5 simples
image = np.array([
    [1, 2, 3, 2, 1],
    [2, 4, 6, 4, 2],
    [3, 6, 9, 6, 3],
    [2, 4, 6, 4, 2],
    [1, 2, 3, 2, 1]
], dtype=float)

In [12]:
img_height, img_width = image.shape
print("Image height: ", img_height)
print("Image width: ", img_width)
k_height, k_width = kernel.shape
print("Kernel height: ", k_height)
print("Kernel width: ", k_width)

Image height:  5
Image width:  5
Kernel height:  3
Kernel width:  3


In [13]:
# Calcula padding necessário
pad_h = k_height // 2
pad_w = k_width // 2
print("Padding height: ", pad_h)
print("Padding width: ", pad_w)

Padding height:  1
Padding width:  1


In [14]:
# Aplica padding por replicação de bordas
padded_image = np.pad(image, ((pad_h, pad_h), (pad_w, pad_w)), mode='edge')
print("Padded image: ")
print(padded_image)

Padded image: 
[[1. 1. 2. 3. 2. 1. 1.]
 [1. 1. 2. 3. 2. 1. 1.]
 [2. 2. 4. 6. 4. 2. 2.]
 [3. 3. 6. 9. 6. 3. 3.]
 [2. 2. 4. 6. 4. 2. 2.]
 [1. 1. 2. 3. 2. 1. 1.]
 [1. 1. 2. 3. 2. 1. 1.]]


In [ ]:
# Inicializa imagem de saída
output = np.zeros_like(image)

# Aplica convolução
for i in range(img_height):
    for j in range(img_width):
        # Extrai região
        region = padded_image[i:i+k_height, j:j+k_width]
        # Multiplica elemento a elemento e soma
        output[i, j] = np.sum(region * kernel)
    